service:
  type: ClusterIP

ingress:
  enabled: true
  tls:
    - hosts:
        - port.exner.dev
      secretName: port-exner-dev-tls
  hosts:
    - host: port.exner.dev
      paths:
        - path: "/"
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    
