providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true 

tlsStore:
  default:
    defaultCertificate:
      secretName: exner-dev-cert-tls
    certificates: 
      - secretName: klara-linus-com-cert-tls



# tlsStore:
#   default:
#     defaultGeneratedCert:
#       resolver: myresolver
#       domain:
#         main: example.org
#         sans:
#           - foo.example.org
#           - bar.example.org



# ports:
#   broker:
#     port: 1883
#     expose: true
#     protocol: TCP
# additionalArguments:
#   - "--entrypoints.broker.address=:1883/tcp"
  # test-udp:
  #   port: 8082
  #   expose: true
  #   protocol: UDP