providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true 

ports:
  broker:
    port: 1883
    expose: true
    protocol: TCP
additionalArguments:
  - "--entrypoints.broker.address=:1883/tcp"
  # test-udp:
  #   port: 8082
  #   expose: true
  #   protocol: UDP