kind: Service
apiVersion: v1
metadata:
  name: fluidd
  namespace: external-service
spec:
  ports:
    - name: fluidd-port
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: fluidd 
  namespace: external-service
subsets:
  - addresses:
      - ip: 192.168.50.121 
    ports:
      - name: fluidd-port
        port: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluidd
  namespace: external-service
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: fluidd.exner.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fluidd
                port:
                  number: 80
  tls:
    - hosts:
        - fluidd.exner.dev
      secretName: fluidd-exner-dev-tls
