apiVersion: v1
kind: Service
metadata:
  name: hass
  namespace: external-service
spec:
  ports:
    - name: hass-port
      protocol: TCP
      port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hass
  namespace: external-service
subsets:
  - addresses:
      - ip: 192.168.50.87 
    ports:
      - name: hass-port
        port: 8123
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass
  namespace: external-service
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: hass.exner.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hass
                port:
                  number: 8123
  tls:
    - hosts:
        - hass.exner.dev
      secretName: hass-exner-dev-tls

