apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:nightly
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: DEFAULT_EMAIL
              value: "liexner@gmail.com"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: mealie-storage
              mountPath: /app/data/
      volumes:
        - name: mealie-storage
          persistentVolumeClaim:
            claimName: mealie  # Reference the PVC

---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
spec:
  selector:
    app: mealie
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

--- #INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  namespace: mealie
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: mealie.exner.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mealie
                port:
                  number: 9000
  tls:
    - hosts:
        - mealie.exner.dev
      secretName: mealie-exner-dev-tls

