apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: mealie
spec:
  #storageClassName: nfs-client #not needed if nfs-provisioner is default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  