apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
      - image: docker/getting-started
        imagePullPolicy: "Always"
        name: getting-started
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: getting-started
  name: getting-started
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: getting-started

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: getting-started
spec:
  # ingressClassName is necessary since v1.22 
  ingressClassName: nginx
  rules:
  - host: test.min.doman.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: getting-started
            port:
              number: 80
