apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: emqx/nanomq
          ports:
            - containerPort: 1883
---


 apiVersion: v1
 kind: Service
 metadata:
   name: broker
   namespace: broker
 spec:
   selector:
     app: broker
   ports:
     - protocol: TCP
       port: 1883
       targetPort: 1883
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: broker
  namespace: broker
spec:
  entryPoints:
    - broker
  routes:
    - match: HostSNI(`*`)
      services:
        - name: broker
          port: 1883
