kind: Service
apiVersion: v1
metadata:
  name: fluidd-service
  namespace: linus
spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: fluidd-service 
  namespace: linus
subsets:
- addresses:
  - ip: 192.168.50.121 
  ports:
  - port: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluidd-ingress
  namespace: linus
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: fluidd.exner.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fluidd-service
                port:
                  number: 80
  tls:
    - hosts:
        - fluidd.exner.dev
      secretName: fluidd-exner-dev-tls
