kind: Service
apiVersion: v1
metadata:
  name: hass-service
  namespace: linus
spec:
 type: ClusterIP
 ports:
 - port: 8123
   targetPort: 8123

---
apiVersion: v1
kind: Endpoints
metadata:
  name: hass-service 
  namespace: linus
subsets:
- addresses:
  - ip: 192.168.50.87 
  ports:
  - port: 8123
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass-ingress
  namespace: linus
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: hass.exner.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hass-service
                port:
                  number: 8123
  tls:
    - hosts:
        - hass.exner.dev
      secretName: hass-exner-dev-tls

