services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped

    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true

      - --entrypoints.websecure.http.tls.domains[0].main=exner.dev
      - --entrypoints.websecure.http.tls.domains[0].sans=*.exner.dev
      - --entrypoints.websecure.http.tls.domains[1].main=klara-linus.com
      - --entrypoints.websecure.http.tls.domains[1].sans=*.klara-linus.com

      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=liexner@gmail.com
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json

      - --providers.file.filename=/config/traefik/dynamic.yml
      - --providers.file.watch=true
    environment:
      - CF_DNS_API_TOKEN=_t12XPa9-QBtgCNDXzocyvd4QBZpX_uvDKGixxqU
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt_cert:/letsencrypt/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/config/traefik/

    networks:
      - proxy

  whoami:
    image: traefik/whoami
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`test.exner.dev`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      # - "traefik.http.middlewares.auth.basicauth.users=liexner:$$2y$$05$$BdY0TFzdWdYj9U5fQVStGuZg3e3v8M2.eRV9fe/QJad1aZc5Z1I7O"
      # - "traefik.http.routers.whoami.middlewares=auth"

  registry:
    image: registry:2
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reg.rule=Host(`reg.exner.dev`)"
      - "traefik.http.routers.reg.entrypoints=websecure"
      - "traefik.http.middlewares.auth.basicauth.users=liexner:$$2y$$05$$BdY0TFzdWdYj9U5fQVStGuZg3e3v8M2.eRV9fe/QJad1aZc5Z1I7O"
      - "traefik.http.routers.reg.middlewares=auth"
    volumes:
      - registry:/var/lib/registry
volumes:
  letsencrypt_cert:
  registry:

networks:
  proxy:
    external: true
