apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: linus
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.41
    path: /home/liexner/kluster-storage
